linuxdeepin/util-dfm

src/dfm-io/dfm-io/utils/dlocalhelper.cpp

If the icon names contains "folder," move it to the front
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-189553.html

fix: [io] Some folder icons are incorrect

---

CMakeLists.txt

`BUILD_UTILS` isn't mentioned anywhere else in this project.

chore: remove unused option from cmake

---

src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/doperator.cpp
src/dfm-io/dfm-io/private/denumerator_p.h

When using an asynchronous iterator, accessing an empty directory received a callback and an error occurred. The error was destructed once and this pointer was used again. Modify and deconstruct after use.
Log: File Manager Crash
Bug: https://pms.uniontech.com/bug-view-198091.html https://pms.uniontech.com/bug-view-198089.html

fix: File Manager Crash

---

src/dfm-mount/private/dnetworkmounter.cpp

anonymous mount a share which have a log sharename will failed, and
'Anonymout not allowed' is reported which is not correct, the real error
should be 'Cannot make dir'.
only report `Anony...` if mount failed with EACCES error.
Log: fix issue about mount error.
Bug: https://pms.uniontech.com/bug-view-201805.html

修复匿名挂载长名共享失败时的错误反馈

---

src/dfm-mount/lib/dblockdevice.cpp

as title.
Log: add more error logs.

当操作设备失败时打印错误信息

---

src/dfm-io/dfm-io/utils/dlocalhelper.cpp

Gio created a temporary. file, but it was soon gone. This is because obtaining the file name for the file is invalid, and there is a problem determining whether it is hidden. Use the URL to obtain the file name of the file.
Log: Hidden files on the desktop flash by
Bug: https://pms.uniontech.com/bug-view-200989.html

fix: [io]Hidden files on the desktop flash by

---

src/dfm-io/dfm-io/dfileinfo.cpp

Failed to retrieve the properties of a hidden file when it does not exist, causing it to be assumed to be non-hidden
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-200989.html

fix: [io] When copying and replacing files, hidden files may display and disappear

---

include/dfm-io/dfm-io/dfile.h
include/dfm-io/dfm-io/dfmio_utils.h
include/dfm-io/dfm-io/doperator.h
src/dfm-io/dfm-io/dfmio_utils.cpp
src/dfm-io/dfm-io/doperator.cpp
src/dfm-io/dfm-io/private/doperator_p.h

1. Modify the copy flag CopyFlag in DFile (modified to match the GFileCopyFlags flag in gio). 2. Modify the copyFile, moveFile, copyFileAsync, and moveFileAsync in the DOperator class to pass in the CopyFlags (interfaces g_file_move and g_file_copy that are compatible with gio) interface. 3. Implement interface cancel in DOperator. 4. Add interfaces deviceNameFromUrl, mountPathFromUrl, and deviceBytesFree to DFMUtils using gio implementation.
Log: MTP file copy optimization
Task: https://pms.uniontech.com/task-view-272307.html

feat: [io]MTP file copy optimization

---

include/dfm-io/dfm-io/denumerator.h
src/dfm-io/dfm-io/utils/dlocalhelper.cpp

Add filesize to sortifno, where you already have the size and can save it in advance. When the file is selected, the file size can be obtained.
Log: Optimization of ctrl+a file operation
Task: https://pms.uniontech.com/task-view-269223.html

feat: [io]Ctrl+a file operation

---

src/dfm-io/dfm-io/utils/dlocalhelper.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.h

When the file manager is closed and the asynchronous thread reads the file attributes in dfmio, a static map is used to convert the string corresponding to the ID. This is because this static map deconstructs and obtains an empty string, causing gio to crash when querying file information assertions. Modify all macros defined by Gio to read properties.
Log: File Manager Crash

fix: [fileinfo]File Manager Crash

---

include/dfm-io/dfm-io/denumerator.h
src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/private/denumerator_p.h

The dfmio Iterator is a gio Iterator created in hasnext. The dde-file-manager does not know when the initialization is complete. Now add a display call.
Log: Add Iterator initialization interface

refactor: Add Iterator initialization interface

---

src/dfm-io/dfm-io/dfileinfo.cpp

1.The search result file does not exist
2.If the absolute path obtained by fileinfo does not exist, the parent directory is obtained, but the format of the returned path is file://xxx.
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-211957.html

fix: [crash] The app crashes when opening the location of the search results file

---

debian/changelog
src/dfm-io/dfm-io/dfileinfo.cpp

Error when fileinfo query is destroyed, didn't bother to determine pointer as nullptr
Log: dde-file-manager crashes when replacing files in vault

fix: [io]dde-file-manager crashes when replacing files in vault

---

include/dfm-io/dfm-io/dfmio_utils.h
src/dfm-io/dfm-io/dfmio_utils.cpp

Files that cannot be deleted to the recycle bin pop up the Delete Completely dialog box.
Log: Files that cannot be deleted to the recycle bin pop up the Delete Completely dialog box.
Task: https://pms.uniontech.com/bug-view-182353.html

feat: [io]Files that cannot be deleted to the recycle bin pop up the Delete Completely dialog.

---

src/dfm-io/dfm-io/dfileinfo.cpp

Asynchronous query for file information in dfmio has an error, didn't call with incoming callback function
Log: Asynchronous query for file information in dfmio has an error, didn't call with incoming callback function

fix: [io/fileinfo]Asynchronous query for file information in dfmio has an error, didn't call with incoming callback function

---

include/dfm-io/dfm-io/dfileinfo.h
src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/dfileinfo.cpp
src/dfm-io/dfm-io/dwatcher.cpp

Calling customAttribute function during asynchronous file info query, refreshing under multithreading causes gfileinfo to destruct
Log: Copying a file to a USB flash drive, the file occasionally flickers
Bug: https://pms.uniontech.com/bug-view-215169.html https://pms.uniontech.com/bug-view-222077.html

fix: [io]Copying a file to a USB flash drive, the file occasionally flickers

---

src/dfm-io/dfm-io/dfileinfo.cpp
src/dfm-io/dfm-io/private/dfileinfo_p.h

The gfileinfo that comes out of the gio asynchronous iteration does not have the accessread, accesswrite, and accesssexecute attributes. Completing these three attributes.
Log: After FTP mounting, I enter the directory without permissions
Bug: https://pms.uniontech.com/bug-view-224901.html

fix: [io]After FTP mounting, I enter the directory without permissions

---

src/dfm-io/dfm-io/dfileinfo.cpp
src/dfm-io/dfm-io/private/dfileinfo_p.h

Reverts linuxdeepin/util-dfm#47
After mounting UOS FTP, the file right-click menu "Cut", "Rename" and "Delete" options are grayed out.
Revert to the old way of getting dfmio file attributes.

Revert "fix: [io]After FTP mounting, I enter the directory without permissions"

---

debian/changelog
src/dfm-mount/lib/dblockdevice.cpp

if the mount point is not empty that means this dev has been mounted
Log: retry the mount process when the auto mount failed
Bug: https://pms.uniontech.com/bug-view-222961.html

fix: [mount] retry the mount process when the auto mount failed

---

src/dfm-burn/dfm-burn-lib/private/dxorrisoengine.cpp

use xorriso -dev /dev/sr0 -format full
Log: blank DVD+RW

fix: [burn] cannot blank DVD+RW

---

include/dfm-io/dfm-io/dfileinfo.h
src/dfm-io/dfm-io/dfileinfo.cpp
src/dfm-io/dfm-io/private/dfileinfo_p.h

When receiving file updates, both the filesortwork thread and the fileinfocache thread call the Gio property acquisition interface simultaneously, causing a crash. Lock when obtaining attributes for dfm-io.
Log: When decompressing a compressed file containing 10000 empty files, the dde-file-manager crashes
Bug: https://pms.uniontech.com/bug-view-237837.html

fix: When decompressing a compressed file containing 10000 empty files, the dde-file-manager crashes

---

src/dfm-mount/lib/dblockmonitor.cpp
src/dfm-mount/lib/dprotocolmonitor.cpp

Fixes these warnings: "warning: ‘QList<T> QSet<T>::toList() const [with T = QString]’ is deprecated: Use values() instead. [-Wdeprecated-declarations]"

fix: use values() instead of deprecated toList()

---

src/dfm-io/dfm-io/dfmio_utils.cpp

1. when the url is trash and has parent dir, the g_file_peek_path while crash.
2. use the g_file_get_path replace g_file_peek_path
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-241241.html

fix: [dfmio] Check thumbail in trash crash

---

src/dfm-burn/3rdparty/udfclient/udf.c

utf-8 suppored
Log: utf-8 suppored for udf2.01

fix: [burn] character set garbling

---

src/dfm-mount/lib/dblockdevice.cpp
src/dfm-mount/private/dblockdevice_p.h

if device has multi mountpoints.
1. the mountPoint function returns the first mountpoint;
2. the mountPoints function returns a list of mountpoints, with the
first mountpoint in the first position.
Log: as title.
Bug: https://pms.uniontech.com/bug-view-248267.html

fix: [248267/mount] always returns the first mountpoint

---

src/dfm-mount/private/dnetworkmounter.cpp

Obtain domain name from configuration file
Log: Get workgroups under the specified configuration file

fix: Obtain domain name when mounting SMB

---

include/dfm-io/dfm-io/error/en.h
src/dfm-io/dfm-io/dfileinfo.cpp

Handle EHOSTDOWN errors
Log: The mounted Samba network disk prompts that the file has been moved or deleted after the user changes their password
Bug: https://pms.uniontech.com/bug-view-261605.html

fix: The mounted Samba network disk prompts that the file has been moved or deleted after the user changes their password

---

src/dfm-mount/private/dnetworkmounter.cpp

Get the smb default domain from smb.conf, and show it.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-263539.html

fix: [smb] Not show smb default domain.

---

src/dfm-mount/lib/dblockdevice.cpp

Logic error. the function use error.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-263863.html

fix: [dfm-mount] can not get part uuid

---

src/dfm-mount/private/dnetworkmounter.cpp

as title.
Log: as title.
Task: https://pms.uniontech.com/task-view-359651.html

feat: [mount] mount by cifs if cifs supported.

---

include/dfm-io/dfm-io/dfmio_utils.h
src/dfm-io/dfm-io/dfmio_utils.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.h

- Add isGvfsFile utility function to detect GVFS paths
- Update symlink handling in DLocalHelper to avoid stat calls on GVFS files
- Add regex pattern to match GVFS paths including /run/user/*/gvfs, /root/.gvfs, and /media/*/smbmounts
This change improves performance by preventing unnecessary stat calls on GVFS symlinks and adds better support for GVFS file system detection.
Log: After the SFTP network was disconnected, dde-file-manager froze
Bug: https://pms.uniontech.com/bug-view-278533.html

fix: After the SFTP network was disconnected, dde-file-manager froze,add GVFS file detection and improve symlink handling

---

src/dfm-io/dfm-io/utils/dlocalhelper.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.h

Updated the comparison functions to handle suffixes correctly.
- Modified `compareByStringEx` to accept additional parameters indicating whether the strings have suffixes.
- Adjusted the logic to prevent sorting by suffixes, ensuring directories are sorted by their names.
- Updated `compareByString` and `compareByName` to pass the new parameters accordingly.
This resolves the issue where directories were incorrectly sorted by suffixes instead of names.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-302719.html

fix: [file-sort] The directory is not sorted by name.

---

src/dfm-io/dfm-io/utils/dlocalhelper.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.h

Modify file size sorting logic to:
- Treat directories as having zero size during comparison
- Add a secondary name-based sorting when file sizes are equal
This change ensures consistent and predictable sorting behavior for files and directories by size.
Log: fix sort issue
Bug: https://pms.uniontech.com/bug-view-306701.html

fix: Improve file size sorting with directory handling

---

src/dfm-mount/lib/dblockmonitor.cpp
src/dfm-mount/private/dblockmonitor_p.h

Implement QDBusServiceWatcher to monitor the UDisks service status. The changes include:
- Starting and stopping device monitoring based on the service owner change.
- Enhanced logging for service status updates.
Log: This addition improves the responsiveness of the block monitor to changes in the UDisks service availability.
Bug: https://pms.uniontech.com/bug-view-307463.html

fix: Add D-Bus service monitoring for UDisks

---

debian/changelog
src/dfm-mount/lib/dblockmonitor.cpp

Refactor the destructor of DBlockMonitorPrivate to call deleteLater on the watcher object, ensuring proper cleanup and avoiding potential crashes. This change enhances the stability of the block monitor during shutdown.

fix: Update DBlockMonitorPrivate destructor to use deleteLater for watcher

---

include/dfm-search/dfm-search/dsearch_global.h
include/dfm-search/dfm-search/filenamesearchapi.h
src/dfm-search/dfm-search-client/main.cpp
src/dfm-search/dfm-search-lib/contentsearch/contentstrategies/indexedstrategy.cpp
src/dfm-search/dfm-search-lib/filenamesearch/filenamesearchengine.cpp
src/dfm-search/dfm-search-lib/filenamesearch/filenamestrategies/indexedstrategy.cpp
src/dfm-search/dfm-search-lib/filenamesearch/filenamestrategies/indexedstrategy.h
src/dfm-search/dfm-search-lib/utils/searchutility.cpp
src/dfm-search/dfm-search-lib/utils/searchutility.h

This commit introduces a new function, `isPinyinSequence`, to validate if a string contains only valid pinyin characters. It includes comprehensive test cases for both valid and invalid pinyin inputs, enhancing the application's ability to handle pinyin searches. Additionally, the search functionality is updated to utilize this new validation method, ensuring that only valid pinyin queries are processed. These changes aim to improve the accuracy and reliability of pinyin-related search operations.
Log: add pinyin check

feat: Implement pinyin sequence validation and testing functionality

---

src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/dfile.cpp
src/dfm-io/dfm-io/dfileinfo.cpp

- Updated checkAndResetCancel() methods in DEnumeratorPrivate, DFilePrivate, and DFileInfoPrivate to improve cancellation logic.
- Now, instead of unreferencing and recreating the cancellable object, the code checks if the cancellable is already cancelled, cancels it if not, and then resets it using g_cancellable_reset().
- This change avoids unnecessary object recreation and ensures proper cancellation state management.
Log: Refactor cancellation handling in DEnumerator, DFile, and DFileInfo

fix: Refactor cancellation handling in DEnumerator, DFile, and DFileInfo

---

debian/changelog
include/dfm-search/dfm-search/dsearch_global.h
src/dfm-search/dfm-search-client/main.cpp
src/dfm-search/dfm-search-lib/utils/searchutility.cpp

This commit introduces a new function, `fileNameIndexStatus`, to retrieve the current indexing status of the file name database. The function checks the availability of the index directory and reads the status from a JSON file, returning the status as a lowercase string. Additionally, a corresponding test function, `testAnythingStatus`, has been implemented to validate the status retrieval process and ensure it returns expected values.
Log: Add file name index status retrieval functionality

feat: Add file name index status retrieval functionality

---

src/dfm-search/dfm-search-lib/contentsearch/contentstrategies/indexedstrategy.cpp
src/dfm-search/dfm-search-lib/filenamesearch/filenamestrategies/indexedstrategy.cpp
src/dfm-search/dfm-search-lib/filenamesearch/filenamestrategies/indexedstrategy.h
src/dfm-search/dfm-search-lib/utils/contenthighlighter.h
src/dfm-search/dfm-search-lib/utils/lucenequeryutils.cpp
src/dfm-search/dfm-search-lib/utils/lucenequeryutils.h

This commit introduces the use of `LuceneQueryUtils` in the `ContentIndexedStrategy` and `QueryBuilder` classes to handle special characters in query strings. The changes replace the previous string processing logic with a more robust method that ensures proper handling of Lucene's syntax, improving the accuracy of search queries. Additionally, redundant string processing methods have been removed to streamline the codebase.
Log:
Bug: https://pms.uniontech.com/bug-view-316553.html

fix: Integrate LuceneQueryUtils for enhanced query string processing

---

src/dfm-search/dfm-search-lib/utils/contenthighlighter.cpp
src/dfm-search/dfm-search-lib/utils/lucenequeryutils.cpp

This commit introduces the `isParagraphStart` function, which checks if a given position in the text content marks the start of a paragraph. The function accounts for whitespace and newline characters to accurately identify paragraph boundaries. Additionally, the `customHighlight` function is updated to prepend an ellipsis when the snippet is truncated at a non-paragraph start position, enhancing the text highlighting feature.
Log:

feat: Add isParagraphStart function to determine paragraph beginnings

---

src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/private/denumerator_p.h

- Introduced OperatorsFileUtils singleton class with delayRemoveCopyingFile method to delay the removal of copying file URLs by 500ms.
- Updated FileOperateBaseWorker to use OperatorsFileUtils::delayRemoveCopyingFile instead of direct FileUtils::removeCopyingFileUrl calls.
- Enhances safety and reliability of file operations by preventing premature removal of file URLs.
Log: add OperatorsFileUtils for delayed removal of copying file URLs
Bug: https://pms.uniontech.com//bug-view-315953.html

fix: add OperatorsFileUtils for delayed removal of copying file URLs

---

src/dfm-mount/lib/dblockdevice.cpp

- Included <sys/statvfs.h> and implemented logic to use statvfs for retrieving filesystem statistics in sizeFree().
- If statvfs succeeds, the free size is calculated using block counts and block size, with a debug message output.
- Falls back to QStorageInfo if statvfs fails.
- Improves accuracy and robustness of free space calculation for block devices.
Log: Add statvfs-based free size calculation in DBlockDevicePrivate::sizeFree
Bug: https://pms.uniontech.com/bug-view-316953.html

fix: Add statvfs-based free size calculation in DBlockDevicePrivate::sizeFree

---

src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/dfile.cpp
src/dfm-io/dfm-io/dfileinfo.cpp
src/dfm-io/dfm-io/private/dfile_p.h
src/dfm-io/dfm-io/trashhelper.cpp
src/dfm-mount/private/dnetworkmounter.cpp

This commit resolves memory leaks by ensuring proper deletion of user data in the `DEnumeratorPrivate::enumUriAsyncCallBack` and `DEnumeratorPrivate::moreFilesCallback` methods. Additionally, the `DFilePrivate` destructor is implemented to clean up GObject resources, including `cancellable`, `iStream`, `oStream`, and `ioStream`. These changes enhance resource management and stability across the affected classes.
Log: fix some memory leaks issue
Bug: https://pms.uniontech.com/bug-view-316919.html

fix: Address memory leaks and resource management in DEnumerator and DFile classes

---

.gitignore
src/dfm-mount/lib/dprotocolmonitor.cpp

This commit updates the type declaration for `entry` in the `DProtocolMonitorPrivate::isNativeMount` method from `GUnixMountEntry_autoptr` to `g_autoptr(GUnixMountEntry)`, ensuring proper memory management and alignment with GObject conventions. Additionally, a new entry for `.cursor` is added to the `.gitignore` file to prevent tracking of cursor files.
Log: Correct GUnixMountEntry type usage in DProtocolMonitor
Bug: https://pms.uniontech.com/bug-view-316919.html

fix: Correct GUnixMountEntry type usage in DProtocolMonitor

---

include/dfm-search/dfm-search/searchoptions.h
src/dfm-search/dfm-search-lib/core/genericsearchengine.cpp
src/dfm-search/dfm-search-lib/core/searchoptions.cpp
src/dfm-search/dfm-search-lib/core/searchoptionsdata.h

This commit adds functionality to set and retrieve the batch processing time interval for asynchronous search operations. The new methods `setBatchTime(int milliseconds)` and `batchTime() const` are implemented in the `SearchOptions` class, allowing users to control the frequency of search result emissions. The default batch time is updated to 1000 milliseconds, and the interval is enforced between 50 and 5000 milliseconds. This enhancement improves the responsiveness of the UI during search operations while allowing for performance optimization based on user preferences.
Log:

feat: Introduce batch processing time configuration for search results

---

debian/control
include/dfm-search/dfm-search/searchoptions.h
src/dfm-search/dfm-search-lib/core/genericsearchengine.cpp
src/dfm-search/dfm-search-lib/core/searchoptions.cpp
src/dfm-search/dfm-search-lib/core/searchoptionsdata.h

- Add batchTime() and setBatchTime() methods to SearchOptions class
- Implement batch time configuration with validation (50-5000ms range)
- Update GenericSearchEngine to use configurable batch time interval
- Change default batch time from 100ms to 1000ms for better performance
- Add libboost-system-dev dependency to debian/control for system components
- Add batchTimeMs field to SearchOptionsData with 1000ms default value
This change allows fine-tuning of search result batching frequency, improving performance for high-volume searches while maintaining UI responsiveness. The configurable interval helps balance between update frequency and system performance.
Log: add configurable batch processing time for search results
Task: https://pms.uniontech.com/task-view-377717.html

feat: add configurable batch processing time for search results

---

debian/changelog
src/dfm-search/dfm-search-lib/utils/searchutility.cpp

This commit modifies the `isFileNameIndexReadyForSearch` function to check if the index status is either "scanning" or "monitoring" instead of just "monitoring". This change improves the flexibility of the index readiness validation, ensuring that the search can proceed under more conditions while providing clearer debug output regarding the expected status.
Log:

fix: Update index readiness check to allow for multiple valid statuses

---

include/dfm-io/dfm-io/dfmio_utils.h
src/dfm-io/dfm-io/dfmio_utils.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.h

- Add symlinkTarget() and resolveSymlink() helpers to resolve symlink chains and detect cycles
- Add fileSizeByEnt() to correctly determine file size for symlinks, including chained symlinks
- Update compareBySize() to use fileSizeByEnt() for accurate sorting
- Refactor createSortFileInfo() to use resolveSymlink() for symlink targets and update file size and isDir accordingly
- Fix stat usage to handle UTF-8 paths and improve symlink resolution logic
- Ensure isDir and isFile are set correctly for symlinks and their targets
These changes improve the accuracy of file size and type detection for symlinks, especially when sorting or displaying file information.
Log: improve symlink handling and file size calculation in DLocalHelper Bug:

fix: improve symlink handling and file size calculation in DLocalHelper

---

src/dfm-search/dfm-search-lib/filenamesearch/filenamestrategies/realtimestrategy.cpp

Add QRegExp::Wildcard flag to QRegExp constructor in matchWildcard method to properly enable wildcard pattern matching functionality for filename search operations.
Log: enable wildcard pattern matching in FileNameRealTimeStrategy
Bug: https://pms.uniontech.com/bug-view-326059.html

fix: enable wildcard pattern matching in FileNameRealTimeStrategy

---

debian/changelog

1. Added new changelog entry for version 1.3.35
2. Documented the bug fix with minimal details
3. Included proper maintainer information and timestamp
4. Following Debian packaging standards for version updates
fix: 更新1.3.35版本的变更日志
1. 为1.3.35版本添加新的变更日志条目
2. 以最少信息记录了错误修复
3. 包含正确的维护者信息和时间戳
4. 遵循Debian打包标准进行版本更新

fix: update changelog for version 1.3.35

---

src/dfm-io/dfm-io/dfileinfo.cpp

1. Added check for url.isLocalFile() before using statx() to avoid invalid file operations on remote files
2. Restructured error handling to return QVariant() early for non-local or invalid cases
3. Simplified the statx success check logic and made it consistent across all attribute methods
4. The changes prevent potential invalid data returns when dealing with remote files since statx is only meant for local filesystem operations
Bug: https://pms.uniontech.com/bug-view-330085.html
fix: 修复非本地文件使用statx导致的异常数据问题
1. 在使用statx()前增加url.isLocalFile()检查，避免对远程文件进行无效操作
2. 重构错误处理逻辑，对非本地或无效情况提前返回QVariant()
3. 简化statx成功检查逻辑，确保所有属性方法处理一致
4. 防止处理远程文件时返回无效数据，因为statx仅适用于本地文件系统操作

fix: prevent statx usage for non-local files

---

include/dfm-io/dfm-io/dfmio_utils.h
src/dfm-io/dfm-io/dfmio_utils.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.cpp

1. Removed the previous file extension splitting logic in DLocalHelper::compareByStringEx that caused incorrect sorting
2. Added a new public method DFMUtils::compareFileName to expose the corrected comparison function
3. Now comparing full strings without separating names and extensions
4. Also fixed URL handling to use toLocal8Bit() instead of toStdString() for better compatibility
The change was necessary because:
1. The old implementation incorrectly sorted files by splitting names and extensions
2. The new approach provides more accurate natural sorting by comparing entire strings
3. Makes the functionality available as a public API for broader use
4. Improves compatibility with various file name encodings
Bug: https://pms.uniontech.com/bug-view-335751.html
fix: 修正文件名比较逻辑
1. 移除 …

fix: correct file name comparison logic
