linuxdeepin/util-dfm

src/dfm-mount/CMakeLists.txt

fix libmount.h: No such file or directory

fix: use pkgconfig to check mount

---

debian/changelog

update the baseline version to 1.2.8
Log: add some async interfaces to support I/O features
Bug: no

feat: update the baseline version to 1.2.8

---

debian/changelog

update the base version to 1.2.9
Log: no
Bug: no

feat: update the base version to 1.2.9

---

src/dfm-io/dfm-io/dwatcher.cpp
src/dfm-io/dfm-io/private/dwatcher_p.h

1.as title
2.Adapt to gvfs modifications
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-189657.html
Bug: https://pms.uniontech.com/bug-view-198635.html

fix: [ftp][watcher] gio can not monitor file changes in the ftp directory

---

src/dfm-io/dfm-io/dwatcher.cpp
src/dfm-io/dfm-io/private/dwatcher_p.h

May consume resources of the inotify instances
Log:

fix: [io][watcher] remove inotify_* from DWatcher

---

src/dfm-mount/private/dnetworkmounter.cpp

as title.
ignore the presetted timeout if user has set one.
Log: charset support for ftp mounts.
Task: https://pms.uniontech.com/task-view-265223.html

完善 dfm-mount 网络挂载的参数处理

---

debian/changelog

update the baseline version to 1.2.10
Log: update the baseline version to 1.2.10
Bug: no

chore: update the baseline version to 1.2.10

---

debian/changelog

update the baseline version to 1.2.11
Log: update the baseline version to 1.2.11
Bug: no

fix: update the baseline version to 1.2.11

---

src/dfm-io/dfm-io/dwatcher.cpp

When monitoring the root directory, the '//' path is monitored. So the file creation monitored is called "//path". Use QUrl:: from LocalFile to convert '//path', and the resulting URL is“ file:///0.0.0/path Modify and process'//'before the path. After processing, make subsequent judgments. If the path is incorrect, reuse the uri.
Log: The newly created file folder in the/directory was not displayed in a timely manner
Bug: https://pms.uniontech.com/bug-view-204961.html

fix: [io/watcher]The newly created file folder in the/directory was not displayed in a timely manner

---

debian/changelog

update baseline version to 1.2.12
Log: update baseline version to 1.2.12
Bug: no

chore: update baseline version to 1.2.12

---

debian/changelog

update the baseline version to 1.2.13
Log: update the baseline version to 1.2.13
Bug: no

chore: update the baseline version to 1.2.13

---

debian/changelog

update the baseline version to 1.2.16
Log: update the baseline version to 1.2.16
Bug: no

chore: update the baseline version to 1.2.16

---

debian/changelog

update the baseline version to 1.2.17
Log: update the baseline version to 1.2.17
Bug: no

chore: update the baseline version to 1.2.17

---

debian/changelog

update the baseline version to 1.2.19
Log: update the baseline version to 1.2.19

chore: update the baseline version to 1.2.19

---

src/dfm-io/dfm-io/doperator.cpp
src/dfm-io/dfm-io/trashhelper.cpp

fix: The destruct mode is wrong

---

debian/changelog
src/dfm-burn/dfm-burn-lib/dopticaldiscinfo.cpp
src/dfm-burn/dfm-burn-lib/private/dopticaldiscinfo_p.h
src/dfm-burn/dfm-burn-lib/private/scsicommandhelper.cpp
src/dfm-burn/dfm-burn-lib/private/scsicommandhelper.h

修复DVD-RW光盘容量问题并升级版本

---

src/dfm-burn/dfm-burn-lib/CMakeLists.txt
src/dfm-io/dfm-io/CMakeLists.txt
src/dfm-mount/CMakeLists.txt

update soname
Log: update soname

fix: update soname

---

debian/changelog

update baseline version to 1.2.22
Log: update baseline version to 1.2.22

chore: update baseline version to 1.2.22

---

debian/changelog

update vresion to 1.2.23
Log:  update vresion to 1.2.23

chore: update vresion to 1.2.23

---

include/dfm-io/dfm-io/dfileinfo.h
src/dfm-io/dfm-io/dfileinfo.cpp

Add original uri attribute
Log: Add original uri attribute

feat: Add original uri attribute

---

debian/changelog

chore: [chglog] update version to 1.2.24

---

debian/changelog

chore: [chglog] update version to 1.2.25

---

debian/changelog

chore: [chglog] update version to 1.3.0

---

include/dfm-mount/dfm-mount/dprotocoldevice.h
src/dfm-mount/lib/dprotocoldevice.cpp
src/dfm-mount/private/dnetworkmounter.cpp
src/dfm-mount/private/dnetworkmounter.h

add ismountbydaemon interface
Log: add ismountbydaemon interface
Bug: https://pms.uniontech.com/bug-view-259823.html

feat: [mount] add ismountbydaemon interface

---

debian/changelog

chore: [chglog] update version to 1.3.1

---

README.md

chore: improve description in README

---

CMakeLists.txt
src/dfm-burn/dfm-burn-client/CMakeLists.txt
src/dfm-burn/dfm-burn-lib/CMakeLists.txt
src/dfm-io/dfm-io/CMakeLists.txt
src/dfm-io/tools/CMakeLists.txt
src/dfm-mount/CMakeLists.txt

Adapt to qt6, modify the deb package name prefix
to dfm6.
Log: Modify the deb package name prefix to dfm6.

chore: [control] change package name prefix

---

debian/changelog

chore: [version] update tag to 1.2.26

---

debian/changelog

chore: [chglog] update version to 1.3.2

---

debian/rules

chore: [debian] update rules

---

debian/control

chore: [debian] update control

---

src/dfm-io/dfm-io/dwatcher.cpp

Implement file monitoring based on different watchtypes
Log: Implement file monitoring based on different watchtypes

fix: Implement file monitoring based on different watchtypes

---

include/dfm-io/dfm-io/denumerator.h
src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/private/denumerator_p.h
src/dfm-io/dfm-io/utils/dlocalhelper.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.h

Add the basic properties of SortFileInfo iterated using fts
Log: The folder opens and loads slowly (it takes a few minutes to load)
Bug: https://pms.uniontech.com/bug-view-259869.html

fix: The folder opens and loads slowly (it takes a few minutes to load)

---

src/dfm-mount/private/dnetworkmounter.cpp

as title.
Log: as title.
Task: https://pms.uniontech.com/task-view-359651.html

feat: [mount] mount by cifs if cifs supported.

---

debian/changelog

chore: [chglog] update version 1.2.27

---

debian/changelog

update tag 1.3.3
Log: update tag 1.3.3

chore: update tag 1.3.3

---

src/dfm-io/dfm-io/dfileinfo.cpp

Adjust format
Log: Adjust format

chore: Adjust format

---

src/dfm-mount/private/dnetworkmounter.cpp

the mountcontrol dbus api has changed.
Log: change mountcontrol dbus api

refactor: change mountcontrol dbus api

---

src/dfm-mount/private/dnetworkmounter.cpp

fix: dbus name error

---

debian/changelog

update version to 1.3.4
Log: update version to 1.3.4

chore: update version to 1.3.4

---

debian/changelog

as above.
Log: bump version to 1.0.36

chore: bump version to 1.0.36

---

src/dfm-io/dfm-io/denumerator.cpp
src/dfm-io/dfm-io/private/denumerator_p.h
src/dfm-io/tools/dfm-list.cpp

- Refactor hasNext() methods in both async and sync modes to use while loops
- Remove recursive calls to hasNext() to avoid potential stack overflow
- Handle empty or invalid file info cases more gracefully
- Improve code readability by restructuring control flow
- Add proper cleanup of GObject resources in all code paths
Log:

refactor: optimize file enumeration logic

---

debian/changelog

chore: update version to 1.3.8

---

.reuse/dep5

remove invalid  url
Log: remove invalid  url

fix: remove invalid  url

---

.reuse/dep5
src/dfm-mount/private/dnetworkmounter.cpp

same as gvfs do.
Log: as above.
Bug: https://pms.uniontech.com/bug-view-294555.html

fix: save samba passwd in cleartext

---

debian/changelog

chore: update version 1.2.28

---

debian/changelog

chore: update version to 1.3.11

---

src/dfm-io/dfm-io/utils/dlocalhelper.cpp
src/dfm-io/dfm-io/utils/dlocalhelper.h

Refactor compareByStringEx to handle high and low surrogate characters more robustly during string comparison. The changes ensure proper string construction and comparison for complex Unicode characters, particularly for full-width and multi-byte characters.
Log: Enhance Unicode sorting logic

fix: Improve Unicode character sorting in file comparison

---

debian/changelog

chore: bump version 1.3.12

---

debian/changelog

Bump version to 1.3.13
Log: Bump version to 1.3.13

chore: Bump version to 1.3.13

---

debian/changelog

chore: bump version to 1.3.15

---

src/dfm-search/dfm-search-lib/core/genericsearchengine.cpp

chore: update doSyncSearch timeout to 30s

---

debian/changelog

chore: bump version to 1.3.17

---

debian/changelog
src/dfm-search/dfm-search-client/main.cpp
src/dfm-search/dfm-search-lib/contentsearch/contentsearchengine.cpp
src/dfm-search/dfm-search-lib/filenamesearch/filenamestrategies/realtimestrategy.cpp
src/dfm-search/dfm-search-lib/filenamesearch/filenamestrategies/realtimestrategy.h

Entering a single Chinese character will still allow full-text searching, while a single English character and number will not.
Log:

feat: Full-text search trigger changed from 2 characters to 2 bytes

---

debian/changelog

chore: bump version to 1.3.23

---

src/dfm-io/dfm-io/utils/dlocalhelper.cpp

add `#include <dfm-io/dfmio_utils.h>`
Log:

chore: fix build failed

---

debian/changelog

chore: bump version to 1.3.36

---

include/dfm-burn/dfm-burn/dburn_global.h
src/dfm-burn/dfm-burn-lib/private/dxorrisoengine.cpp

add `DVD_R_DL` media tpye
Log: add `DVD_R_DL` media tpye
Task: https://pms.uniontech.com/task-view-380333.html

feat: [burn] add `DVD_R_DL` media tpye

---

debian/changelog

chore: update version 1.2.29

---

debian/changelog

chore: update version 1.2.30
